{
 "title": "FastAPI - Logs Dashboard",
 "tags": [
  "logs",
  "application"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "search_query", "label": "Search Query" },
   { "name": "job", "label": "Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Log Rate by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({job=~\".+\"}[1m])) by (level)"
    }
   ]
  },
  {
   "title": "Recent Error Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=~\".+\"}\n| json \n| record_level_name = \"ERROR\" \n| line_format \"Time: {{.record_time_repr}} | Level: {{.record_level_name}} | Source: {{.record_extra_source}} | Path: {{.record_file_path}} | Process ID: {{.record_process_id}} | Thread ID: {{.record_thread_id}} | Message: {{.record_message}}\""
    }
   ]
  },
  {
   "title": "All Application Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=~\".+\"} |~ \"$search_query\""
    }
   ]
  }
 ]
}